version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    container_name: foodgram_db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram_backend
    image: ak1korn/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/

  frontend:
    container_name: foodgram_frontend
    image: ak1korn/foodgram_frontend
    depends_on:
      - backend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    container_name: foodgram_nginx
    image: ak1korn/foodgram_nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - static:/staticfiles/
      - media:/app/media/
    ports:
      - 8000:80
